### ISSUE TITLE
Some enhancements

### ISSUE THREAD

**Issue by ishita1818** [NJACKWinterOfCode/Memegenerator#11]
- Image saving option
   We can have the generate button as preview button and the current resultant image as the preview and then we can provide edit option after which user can save the image.         

- Image crop option

- Text colors (Since there are possibilities for the image to be black at top and bottom)

**Comment by madhavrathi** [comment]
@ishita1818 Go ahead 👍

**Comment by ishita1818** [comment]
@madhavrathi I have completed the part of saving and sharing the image. Can i send a pull request so that you can review it or shall I complete it first?

**Comment by ishita1818** [comment]
These are some of the screenshots:-

![screenshot_20171214-213318 1](https://user-images.githubusercontent.com/29219860/34001653-8d804fee-e116-11e7-8253-8e3070c12d80.png)

![screenshot_20171214-213309 1](https://user-images.githubusercontent.com/29219860/34001749-cf3f6f8c-e116-11e7-9e1d-cb9603707bc7.png)

![screenshot_20171214-213246 1](https://user-images.githubusercontent.com/29219860/34001856-20f31194-e117-11e7-8452-3f000deb9c4d.png)

![screenshot_20171214-213241 1](https://user-images.githubusercontent.com/29219860/34001971-710277c4-e117-11e7-9653-2f6e1496c16a.png)

**Comment by madhavrathi** [comment]
@ishita1818 you send can PR. Great work :+1:

**Comment by ishita1818** [comment]
@madhavrathi okay :)

**Comment by ishita1818** [comment]
@madhavrathi I am still working upon the cropping part.. this issue has not been solved yet. Can you please reopen this?

**Comment by ishita1818** [comment]
#21 will fix this issue. @madhavrathi you can close this as soon as my PR gets merged.
