### ISSUE TITLE
Design App logo

### ISSUE THREAD

**Issue by ishita1818** [NJACKWinterOfCode/Memegenerator#13]
We should also add a cool logo for app.

**Comment by ishita1818** [comment]
-  1

![memegeneratorlogo7](https://user-images.githubusercontent.com/29219860/34072914-a928c7bc-e2b5-11e7-85ea-ca93b83572a4.png)

- 2

![memegeneratorlogo1](https://user-images.githubusercontent.com/29219860/34072883-52893e50-e2b5-11e7-9441-adf426cd84b0.png)

- 3

![memegeneratorlogo2](https://user-images.githubusercontent.com/29219860/34072885-59b44576-e2b5-11e7-95ef-4c5b6b770aa8.png)

- 4

![memegeneratorlogo4](https://user-images.githubusercontent.com/29219860/34072887-60c4b300-e2b5-11e7-908d-95ad17e75d4d.png)

- 5

![memegeneratorlogo3](https://user-images.githubusercontent.com/29219860/34072913-9ba24956-e2b5-11e7-963b-26c2d08e3d57.png)

- 6

![memegeneratorlogo5](https://user-images.githubusercontent.com/29219860/34072903-7cebb114-e2b5-11e7-8950-a2867331245a.png)

- 7

![memegeneratorlogo6](https://user-images.githubusercontent.com/29219860/34072909-8bc4a27c-e2b5-11e7-87ed-5d50aeed0f41.png)

- 8

![memegeneratorlogo8](https://user-images.githubusercontent.com/29219860/34072920-c49fdf8a-e2b5-11e7-8a8a-05d4912f7329.png)

- 9

![memegeneratorlogo9](https://user-images.githubusercontent.com/29219860/34072923-cb68e4ce-e2b5-11e7-9a60-e05721f0f6f9.png)

@madhavrathi Can you suggest which one should be added ?

**Comment by madhavrathi** [comment]
@ishita1818 we should design a logo for app. Since this is an open source app. We should refrain from using images that we do not own or are not freely available.

**Comment by ishita1818** [comment]
Okay! got it.

**Comment by AK-007** [comment]
@madhavrathi This will be simple and effective.
![meme](https://user-images.githubusercontent.com/26346816/34411184-1c829d02-ebfb-11e7-9876-459018606ea4.png)

**Comment by madhavrathi** [comment]
@AK-007 Looks good to me. Take reviews from other devs as well. Cheers!

**Comment by ishita1818** [comment]
![memeholic](https://user-images.githubusercontent.com/29219860/34414555-012d5758-ec10-11e7-9ed8-5bcb264cdfc6.png)
 What about this one since this also matches with our app theme colors.
@madhavrathi

**Comment by madhavrathi** [comment]
Well simply having "M" does not signifies the purpose of the app. Maybe we can add full "Meme" text in logos with abstract background.

**Comment by ishita1818** [comment]
![rsz_screenshot_70](https://user-images.githubusercontent.com/29219860/34417152-f873da6c-ec1c-11e7-885a-53bff95281fe.png)
 @madhavrathi So I came up with this... how is it?

**Comment by AK-007** [comment]
@madhavrathi Should I create a PR?

**Comment by ishita1818** [comment]
@AK-007 Please can I have a look upon the icon you will be updating for the app.

**Comment by Logan1x** [comment]
I personally like [this one](https://github.com/NJACKWinterOfCode/Memegenerator/issues/13#issuecomment-354283202) @AK-007  did you made this one because if we gonna use it, it should be copyright claim free.

**Comment by AK-007** [comment]
@Logan1x  yeah I made that myself using Adobe llustrator.There will be no copyright issues.

**Comment by Logan1x** [comment]
@AK-007  That's So great. If @madhavrathi approves this then we can go ahead with this.In future, I would love to see updates for this logo.

**Comment by madhavrathi** [comment]
Please go ahead with this. There's always a room for improvement. Cheers !

**Comment by Logan1x** [comment]
@AK-007  Time to send a PR🎉
