### ISSUE TITLE
Search for image within the app

### ISSUE THREAD

**Issue by ishita1818** [NJACKWinterOfCode/Memegenerator#18]
What if we let the user search for the required image within our app so that he doesn't have to download an image externally and then use our app to edit it.
@madhavrathi How's this ?

**Comment by ishita1818** [comment]
@madhavrathi Can i proceed further in this way?

**Comment by ishita1818** [comment]
@madhavrathi Can I work upon this thing?

**Comment by madhavrathi** [comment]
SURE, we can use a free image Api to get related images according to a keyword. I know this Getty images API. Check that out. Cheers!

**Comment by ishita1818** [comment]
Okay... there are many such API's, thanks for suggesting this one. I will have a look upon it also.
