### ISSUE TITLE
Make Facebook developer account for sdk use.

### ISSUE THREAD

**Issue by Kartikdot** [NJACKWinterOfCode/Memegenerator#19]
Would i like to work on it? Yes

**Comment by ishita1818** [comment]
@Kartik2016 Have you tested the sharing on facebook?
Since, I am not able to do so... it just shows a toast message of "Meme saved!".
Am I doing something wrong...?

**Comment by Kartikdot** [comment]
Yes i tested it. It was working fine. However i think there might be some setting in the developer account that turns the make app live option turn off automatically. I'll look into and make the required changes tommorow. Thanks for reporting!

**Comment by Kartikdot** [comment]
So i checked and facebook blocked the account due to "multiple login attempts from various devices" I guess i'll shift it back to my account for the time being,
