### ISSUE TITLE
 Add export options for social media

### ISSUE THREAD

**Issue by madhavrathi** [NJACKWinterOfCode/Memegenerator#4]
Add export option for memes generated so that they can be published directly on Instagram, Facebook and other social platforms

**Comment by Kartikdot** [comment]
I would like to work on this.

**Comment by madhavrathi** [comment]
Go ahead :+1:

**Comment by Kartikdot** [comment]
Also, this issue involves making new menu resource file, working with the action bar, handling the image properly to send and working with intents. I think it should be labeled as intermediate?

**Comment by Kartikdot** [comment]
@madhavrathi This issue seems to have been fixed while i was already working on it. I don't think this is in line with open source ethics. The contributer should have asked in the comments before making a PR. Thoughts?

**Comment by madhavrathi** [comment]
@Karthik2016 I am really sorry. You are right. I seriously forgot that you were working on this, otherwise I would have mentioned it somewhere. @ishita1818 @Karthik2016 I request all the developers to check the existing issues before making a PR. @Karthik2016 FB export option is still remaining. You can work on that.

**Comment by ishita1818** [comment]
Ya okay @madhavrathi . But i haven't added **export options** , I have just added _sharing functionality_ like by WhatsApp, email, bluetooth, drive etc. So, this issue hasen't been fixed yet.
 @Kartik2016

**Comment by Kartikdot** [comment]
Ok sure. I'll work on it. Currently there is an option to share on facebook. Selecting it opens facebook but does not display the image in the post. That's what needs to be fixed right?

**Comment by ishita1818** [comment]
Nops, by the latest updated code, there is a share icon, clicking upon which, user can share the image via some medium.
You have to add the whole functionality of sharing to facebook.

**Comment by Kartikdot** [comment]
Just to be clear i do not need to add another button? If after clicking the share button the user selects facebook from the option of mediums, then that functionality is what i have to write?

**Comment by ishita1818** [comment]
Better will be if you add another button, since this share button deals with intents. And sharing on facebook is a whole different thing.

**Comment by Kartikdot** [comment]
Yes that was also what i was thinking! Cool i'll start working on it. Thanks for the help.

**Comment by ishita1818** [comment]
No issues... :)
