### ISSUE TITLE
Select Image from gallery and text style

### ISSUE THREAD

**Issue by anandwana001** [NJACKWinterOfCode/Memegenerator#8]
@madhavrathi This app not allow changing the image and text style. I would like to work on this where the user can select any image from gallery and then add top and bottom text with style.

**Comment by Akshat-Jain** [comment]
I've already done these changes. Please check out the latest commits. Thanks :-)

**Comment by anandwana001** [comment]
@Akshat-Jain could you please share the screenshots? and if your PR gets merge please update those screenshot in README file

**Comment by Akshat-Jain** [comment]
You can see the screenshot attached. And yeah sure, I'll update the README
file whenever my PR gets merged. Thanks..!

On 13-Dec-2017 10:25 AM, "Akshay Nandwana" <notifications@github.com> wrote:

@Akshat-Jain <https://github.com/akshat-jain> could you please share the
screenshots? and if your PR gets merge please update those screenshot in
README file

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NJACKWinterOfCode/Memegenerator/issues/8#issuecomment-351282371>,
or mute the thread

**Comment by Akshat-Jain** [comment]
![screenshot_20171213-102656](https://user-images.githubusercontent.com/31135861/33922415-bd3be54e-dff0-11e7-84af-92ebce45cabd.png)

**Comment by anandwana001** [comment]
@Akshat-Jain and what about the font style?

**Comment by Akshat-Jain** [comment]
I'm using the font "Impact" which is the standard font for Memes. Already done this change in the PR.

**Comment by anandwana001** [comment]
@Akshat-Jain @madhavrathi  I mean to implement a feature where a user can select font style, color. Fixing only one font in app doesn't bring any impact on the user, user may look forward to more interesting things in app

**Comment by Akshat-Jain** [comment]
I actually thought about trying to add an option which gives users the
chance to select custom font style and colour. But I haven't seen any meme
which doesn't use "Impact" fontStyle. Plus the color I'm using right now
would be visible on all background images, and this also, is kinda standard
for Memes (white colour text with thin black borders).

**Comment by anandwana001** [comment]
@Akshat-Jain @madhavrathi yes, it's all up to mentor, they want to implement new feature in application or make the app standard!!

**Comment by Akshat-Jain** [comment]
Yeah :-)

**Comment by madhavrathi** [comment]
@anandwana001 @Akshat-Jain Do what you please and discuss among yourself. You do not need my permission for adding or deleting any feature. Proceed with your ideas 👍

**Comment by ishita1818** [comment]
@madhavrathi I guess this is resolved now..?

**Comment by madhavrathi** [comment]
I was keeping it open for discussion. Guess there is no more :p
